# Generated by Django 3.2 on 2021-04-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BecaModel',
            fields=[
                ('beca_id', models.AutoField(primary_key=True, serialize=False)),
                ('beca_name', models.TextField(max_length=50)),
                ('beca_lname', models.TextField(max_length=50)),
                ('beca_date', models.DateField()),
                ('beca_gender', models.TextField(max_length=10)),
                ('beca_citizenship', models.TextField(max_length=50)),
                ('beca_country', models.TextField(max_length=50)),
                ('beca_curriculum', models.Field()),
                ('beca_message', models.TextField()),
            ],
        ),
    ]
